/* conff.c - Maintain configuration information
   Copyright (C) 2000 Thomas Moestl

This file is part of the pdnsd package.

pdnsd is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

pdnsd is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with pdsnd; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.  */

#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "ipvers.h"
#include "conff.h"
#include "consts.h"
#include "helpers.h"
#include "y.tab.h"

#if !defined(lint) && !defined(NO_RCSIDS)
static char rcsid[]="$Id: conff.c,v 1.12 2000/07/07 10:05:35 thomas Exp $";
#endif

#ifndef CACHEDIR
#error "CACHEDIR must be defined. Please look into your Makefile!"
#endif
#ifdef ENABLE_IPV4
globparm_t global={2048,CACHEDIR,53,{{INADDR_ANY}},0,604800,"",1,0};
#else
globparm_t global={2048,CACHEDIR,53,{IN6ADDR_ANY_INIT},0,604800,"",1,0};
#endif
servparm_t server;
#ifdef ENABLE_IPV4
servparm_t serv_presets={53,C_NONE,120,900,600,"","","",0,0,1,1,0,{{INADDR_ANY}},{{INADDR_ANY}}};
#else
servparm_t serv_presets={53,C_NONE,120,900,600,"","","",0,0,1,1,0,{IN6ADDR_ANY_INIT},{IN6ADDR_ANY_INIT}};
#endif

int serv_num=0;
servparm_t *servers=NULL;

void lex_set_io(FILE *in, FILE *out); /* defined in conf.l*/
int  yyparse (void);                  /* from yacc/bison output */

/* Initialize a servparm_t */
void set_serv_presets(servparm_t *server)
{
	*server=serv_presets;
#if defined(ENABLE_IPV4) && defined(ENABLE_IPV6)
	/* In this case we have to set IN6ADDR_ANY_INIT */
	if (run_ipv6) {
		server->a.ipv6=server->ping_a.ipv6=in6addr_any;
	}
#endif
}

/*
 * Add a server (with parameters contained in serv) into the internal server-list
 * (in the pointer servers)
 */
void add_server(servparm_t serv)
{
	serv_num++;
	if (!(servers=realloc(servers,sizeof(servparm_t)*serv_num))) {
		fprintf(stderr,"Error: out of memory.\n");
		exit(1);
	}
	servers[serv_num-1]=serv;
}

/*
 * Read a configuration file and save the result. This uses the parser generated by yacc/bison
 * from conf.y, which in turn uses the lexer generated lex/flex from conf.l
 */
void read_config_file(char *nm)
{
	FILE *in;
	struct stat sb;
	if (nm==NULL) {
		nm="/etc/pdnsd.conf";
	} 
	if (stat(nm,&sb)!=0) {
		fprintf(stderr,"Error: Could not stat conf file %s: %s\n",nm,strerror(errno));
		exit(3);
	}
	if (sb.st_uid!=getuid()) {
		fprintf(stderr,"Error: You must own the config file.\n");
		exit(3);
	}
	if ((sb.st_mode&S_IWGRP) || (sb.st_mode&S_IWOTH)) {
		fprintf(stderr,"Error: Bad config file permissions: the file must be only writeable by the user.\n");
		exit(3);
	}
	if (!(in=fopen(nm,"r"))) {
		fprintf(stderr,"Error: Could not open conf file %s: %s\n",nm,strerror(errno));
		exit(3);
	}
	lex_set_io(in,stdout);
	if (yyparse())
		exit(3);
	fclose(in);
}

/* Report the currenct configuration into the file (for the status fifo, see status.c) */
void report_conf_stat(FILE *f)
{
	char buf[ADDRSTR_MAXLEN];
	int i;
	fprintf(f,"\nConfiguration:\n==============\nGlobal:\n-------\n");
	fprintf(f,"\tCache size: %li kB\n",global.perm_cache);
	fprintf(f,"\tServer directory: %s\n",global.cache_dir);
	fprintf(f,"\tServer port: %i\n",global.port);
	fprintf(f,"\tIgnore cache when link is down: %i\n",global.lndown_kluge);
	fprintf(f,"\tMaximum ttl: %li\n",global.max_ttl);
	fprintf(f,"\tRun as: %s\n",global.run_as);
	fprintf(f,"\tStrict run as: %i\n",global.strict_suid);
	fprintf(f,"\tParanoid mode (cache pollution prevention): %i\n",global.paranoid);
	for(i=0;i<serv_num;i++) {
		fprintf(f,"Server %i:\n------\n",i+1);
		fprintf(f,"\tip: %s\n",pdnsd_a2str(&servers[i].a,buf,ADDRSTR_MAXLEN));
		fprintf(f,"\tport: %hu\n",servers[i].port);
		fprintf(f,"\tuptest: %i\n",servers[i].uptest);
		fprintf(f,"\ttimeout: %li\n",servers[i].timeout);
		fprintf(f,"\tpurge interval: %li\n",servers[i].interval);
		fprintf(f,"\tping timeout: %li\n",servers[i].ping_timeout);
		fprintf(f,"\tping ip: %s\n",pdnsd_a2str(&servers[i].ping_a,buf,ADDRSTR_MAXLEN));
		fprintf(f,"\tinterface: %s\n",servers[i].interface);
		fprintf(f,"\tuptest command: %s\n",servers[i].uptest_cmd);
		fprintf(f,"\tuptest user: %s\n",servers[i].uptest_usr[0]?servers[i].uptest_usr:"(process owner)");
		fprintf(f,"\tforce cache purging: %i\n",servers[i].purge_cache);
		fprintf(f,"\tserver is cached: %i\n",!servers[i].nocache);
		fprintf(f,"\tlean query: %i\n",!servers[i].lean_query);
		fprintf(f,"\tserver assumed available: %i\n",servers[i].is_up);
	}
}
