#!/bin/sh

# $Id: pdnsd,v 1.2 2000/07/22 10:10:16 thomas Exp $
#
# This script was written and contributed by Markus Mohr, and
# slightly modified by me for version 1.0.6 (which obviously
# broke it some way). I then applied a set of corrections
# by Markus Mohr.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

test -x /usr/sbin/pdnsd || exit 0

case "$1" in
    start)
    	# Check if cache dir exists and recreate if neccessary
	test -d /var/cache/pdnsd || mkdir /var/cache/pdnsd
	chown nobody /var/cache/pdnsd
	echo -n "Starting domain name service: pdnsd"
	start-stop-daemon --start --quiet --pidfile /var/run/pdnsd.pid --name pdnsd \
	--exec /usr/sbin/pdnsd -- --daemon -p /var/run/pdnsd.pid \
	|| echo -n " already running"
	echo "."
    ;;

    stop)
	echo -n "Stopping domain name service: pdnsd"
	start-stop-daemon --stop --quiet  --pidfile /var/run/pdnsd.pid --name pdnsd --exec /usr/sbin/pdnsd \
	|| echo -n " not running"
	echo "."
    ;;

    restart)
        $0 stop
	$0 start
    ;;
    
    *)
	echo "Usage: /etc/init.d/pdnsd {start|stop|restart}" >&2
	exit 1
    ;;
esac

exit 0
