/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.4 1999/10/27 07:56:44 obrien Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
static yyconst short int yy_acclist[552] =
    {   0,
       81,   79,   80,   77,   79,   80,   78,   80,   79,   80,
       73,   79,   80,   72,   79,   80,   79,   80,    1,   79,
       80,   70,   79,   80,   57,   70,   79,   80,   70,   79,
       80,   70,   79,   80,   70,   79,   80,   70,   79,   80,
       70,   79,   80,   70,   79,   80,   70,   79,   80,   70,
       79,   80,   70,   79,   80,   70,   79,   80,   70,   79,
       80,   70,   79,   80,   70,   79,   80,   70,   79,   80,
       70,   79,   80,   70,   79,   80,   70,   79,   80,   76,
       79,   80,   76,   77,   79,   80,   76,   79,   80,   76,
       79,   80,   77,   71,   73,   74,   73,    1,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       37,   70,   70,   70,   70,   70,   70,   59,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,    4,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   75,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,    5,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   58,   70,   70,   70,   70,
       70,   70,   70,   61,   70,   70,   70,   70,   70,   70,
       64,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       70,   70,   70,   70,   66,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   62,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   38,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   60,   70,   70,   70,
       25,   70,   70,   70,   70,   70,   70,   70,   56,   70,
       70,   70,   70,   70,   70,   70,   70,   63,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   65,   70,   70,   70,   70,   70,   70,   70,

       19,   70,   47,   70,   69,   70,   70,    2,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   55,   70,   51,   70,   70,
       70,   70,   70,   70,   70,   15,   70,   70,   39,   70,
       70,    3,   70,    6,   70,   70,   70,   70,   70,   70,
       40,   70,   70,   68,   70,   70,   49,   70,   70,   54,
       70,   53,   70,   70,   70,   70,   70,   13,   70,   14,
       70,   70,   70,   32,   70,   70,   70,   70,   70,   43,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   41,   70,   70,

       70,   70,   70,   70,   45,   70,   70,   70,   70,   70,
       70,   17,   70,   70,   21,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   24,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,    8,   70,   26,   70,   46,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   10,   70,   70,
       70,   70,   70,   70,   70,   22,   70,   50,   70,   70,
       70,   70,   70,    7,   70,   70,   27,   70,   70,   52,
       70,   70,   70,   70,   70,   70,   70,   70,   18,   70,
       70,   70,   20,   70,   44,   70,   70,   70,   33,   70,

       30,   70,   70,   28,   70,   48,   70,   70,   70,   70,
       11,   70,   70,    9,   70,   70,   70,   70,   70,   42,
       70,   23,   70,   70,   70,   70,   70,   70,   29,   70,
       70,   70,   70,   70,   70,   67,   70,   16,   70,   12,
       70,   34,   70,   36,   70,   70,   31,   70,   70,   35,
       70
    } ;

static yyconst short int yy_accept[433] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   11,
       14,   17,   19,   22,   25,   29,   32,   35,   38,   41,
       44,   47,   50,   53,   56,   59,   62,   65,   68,   71,
       74,   77,   80,   83,   87,   90,   93,   94,   94,   95,
       96,   97,   98,   99,  100,  101,  102,  103,  104,  105,
      106,  107,  108,  109,  110,  111,  113,  114,  115,  116,
      117,  118,  120,  121,  122,  123,  124,  125,  126,  127,
      128,  129,  130,  131,  132,  134,  135,  136,  137,  138,
      139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  150,  151,  152,  153,  154,  155,  156,  157,  158,

      159,  160,  161,  162,  163,  164,  165,  167,  168,  169,
      170,  171,  172,  173,  174,  175,  176,  178,  179,  180,
      181,  182,  183,  184,  186,  187,  188,  189,  190,  191,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  207,  208,  209,  210,  211,  212,  213,
      214,  215,  217,  218,  219,  220,  221,  222,  223,  224,
      225,  227,  228,  229,  230,  231,  232,  233,  234,  235,
      236,  237,  238,  239,  240,  241,  242,  243,  244,  245,
      246,  247,  249,  250,  251,  253,  254,  255,  256,  257,
      258,  259,  261,  262,  263,  264,  265,  266,  267,  268,

      270,  271,  272,  273,  274,  275,  276,  277,  278,  279,
      280,  281,  282,  283,  284,  285,  286,  287,  288,  289,
      290,  291,  292,  293,  295,  296,  297,  298,  299,  300,
      301,  303,  305,  307,  308,  310,  311,  312,  313,  314,
      315,  316,  317,  318,  319,  320,  321,  322,  323,  324,
      325,  326,  328,  330,  331,  332,  333,  334,  335,  336,
      338,  339,  341,  342,  344,  346,  347,  348,  349,  350,
      351,  353,  354,  356,  357,  359,  360,  362,  364,  365,
      366,  367,  368,  370,  372,  373,  374,  376,  377,  378,
      379,  380,  382,  383,  384,  385,  386,  387,  388,  389,

      390,  391,  392,  393,  394,  395,  396,  397,  398,  400,
      401,  402,  403,  404,  405,  407,  408,  409,  410,  411,
      412,  414,  415,  417,  418,  419,  420,  421,  422,  423,
      424,  425,  426,  427,  428,  429,  430,  431,  432,  433,
      434,  435,  436,  438,  440,  442,  443,  444,  445,  446,
      447,  448,  449,  450,  451,  452,  453,  454,  455,  456,
      457,  458,  460,  461,  462,  463,  464,  465,  466,  468,
      470,  471,  472,  473,  474,  476,  477,  479,  480,  482,
      483,  484,  485,  486,  487,  488,  489,  491,  492,  493,
      495,  497,  498,  499,  501,  503,  504,  506,  508,  509,

      510,  511,  513,  514,  516,  517,  518,  519,  520,  522,
      524,  525,  526,  527,  528,  529,  531,  532,  533,  534,
      535,  536,  538,  540,  542,  544,  546,  547,  549,  550,
      552,  552
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    1,    7,    1,    1,    8,    9,    9,    9,
        9,   10,    9,    9,    9,    9,    9,    1,    7,    1,
        7,    1,    1,    1,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        1,    1,    1,    1,   12,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   11,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,    7,    1,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[436] =
    {   0,
        0,    0,   36,   43,  453,  454,  450,  454,  447,    0,
      454,   35,   38,    0,  418,   27,   37,  414,  427,  424,
       28,   43,   44,   49,  412,   67,  413,   46,   55,   46,
      417,  426,  454,  440,  433,  434,  437,  434,  454,    0,
      454,    0,   59,    0,  406,  421,  422,  411,  416,   57,
      408,  416,  407,  403,   58,    0,  414,  414,  401,  390,
      399,    0,  399,  403,  396,  391,  390,   58,   62,   75,
      389,  388,  399,  390,    0,  389,  393,  383,   63,   74,
      384,  386,  386,  381,  376,  377,  454,  385,  384,  379,
      390,  377,  368,  378,  385,  374,  379,  381,  371,  376,

      375,  366,  368,  377,  376,  370,  374,  368,   92,  360,
      371,  363,  360,  349,  349,   79,    0,  359,  348,  360,
      363,  357,  340,    0,  343,  340,  349,  357,  351,    0,
      350,  349,  351,  335,   85,  346,  335,  335,  341,  344,
      337,  325,    0,  343,  323,  325,  330,  340,  335,  319,
      318,    0,   81,  319,  319,  321,  333,  326,  331,  327,
        0,  324,   88,  304,  322,  302,  311,   94,  312,  318,
      319,  301,  317,   81,  305,  300,  299,  302,  310,  314,
      300,    0,  307,  298,    0,  305,  296,  304,  296,  302,
       90,    0,  289,  290,  284,  283,  287,  283,  280,    0,

      278,  283,  293,  286,   96,  270,  274,  281,  291,  290,
      289,  288,  275,  268,  270,  279,  101,  278,  264,  262,
      261,  274,  258,    0,  258,  258,  272,  270,  266,  255,
        0,    0,    0,  266,    0,  265,  268,  267,  247,  244,
      254,  253,  251,  244,  250,  255,  250,  257,  246,  241,
      246,    0,    0,  245,  242,  238,  248,   94,  241,    0,
      228,  248,  246,  246,    0,  245,  244,  234,  225,  222,
      240,  230,    0,  229,    0,  225,    0,    0,  233,  224,
      229,  220,    0,    0,  231,  231,    0,  213,  225,  225,
      222,    0,  214,  213,  215,  210,  221,  216,  206,  194,

      220,  211,  205,   98,  212,  196,  201,  191,    0,  208,
      191,  192,  190,  202,    0,  189,  205,  195,  188,  193,
        0,  193,    0,  195,  190,  186,  186,  193,  176,  177,
      188,  454,  183,  182,  175,  175,  169,  182,  181,  180,
      172,  159,    0,    0,    0,  158,  171,  167,  165,  173,
      172,  162,  156,  165,  149,  164,  163,  151,  169,  157,
      166,    0,  149,  154,  145,  149,  145,  157,    0,    0,
      149,  159,  147,  139,    0,  136,    0,  136,    0,  149,
      139,  152,  134,  145,  131,  129,    0,  127,  126,    0,
        0,  125,  129,    0,    0,  124,    0,    0,  138,  103,

      136,    0,  135,    0,  130,  119,  130,  122,    0,    0,
      122,  115,  130,  114,  127,    0,  124,  109,  115,  116,
       98,    0,    0,    0,    0,    0,   97,    0,   93,    0,
      454,  133,  136,  139,  119
    } ;

static yyconst short int yy_def[436] =
    {   0,
      431,    1,  432,  432,  431,  431,  431,  431,  433,  434,
      431,  431,  431,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  431,  431,  431,  431,  431,  433,  431,  434,
      431,  434,  431,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  431,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  431,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
        0,  431,  431,  431,  431
    } ;

static yyconst short int yy_nxt[492] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   13,
       14,   14,   15,   14,   16,   17,   18,   19,   20,   14,
       21,   14,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   14,   14,   14,   14,   34,    8,   46,
       41,   35,   42,   36,   34,    8,   43,   43,   35,   49,
       36,   47,   55,   50,   56,   57,   60,   48,   74,   58,
       81,   63,   51,   59,   61,   64,   82,   43,   43,   77,
       93,   78,   99,  111,   75,  124,   83,   76,   62,   66,
       79,   84,  112,   67,  113,   80,  126,   68,  100,   94,
      114,  115,   69,  163,  125,   70,  197,   71,   72,  208,

      116,  180,  127,  155,  156,  181,  214,  237,  221,  198,
      222,  199,  263,  164,  215,  209,  250,  298,  335,  411,
      299,   44,  238,  430,  336,  429,  251,  428,  427,  264,
      426,  425,  412,   33,   33,   33,   38,   38,   38,   40,
      424,   40,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,

      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  262,  261,  260,  259,  258,

      257,  256,  255,  254,  253,  252,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  220,  219,  218,  217,  216,  213,  212,  211,  210,
      207,  206,  205,  204,  203,  202,  201,  200,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  162,  161,
      160,  159,  158,  157,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,

      138,  137,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  123,  122,  121,  120,  119,  118,  117,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,   98,   97,
       96,   95,   92,   91,   90,   89,   88,   39,   37,   41,
       87,   37,   86,   85,   73,   65,   54,   53,   52,   45,
       39,   37,  431,    5,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431

    } ;

static yyconst short int yy_chk[492] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,   16,
       12,    3,   12,    3,    4,    4,   13,   13,    4,   17,
        4,   16,   21,   17,   21,   22,   23,   16,   28,   22,
       30,   24,   17,   22,   23,   24,   30,   43,   43,   29,
       50,   29,   55,   68,   28,   79,   30,   28,   23,   26,
       29,   30,   68,   26,   69,   29,   80,   26,   55,   50,
       69,   70,   26,  116,   79,   26,  153,   26,   26,  163,

       70,  135,   80,  109,  109,  135,  168,  191,  174,  153,
      174,  153,  217,  116,  168,  163,  205,  258,  304,  400,
      258,  435,  191,  429,  304,  427,  205,  421,  420,  217,
      419,  418,  400,  432,  432,  432,  433,  433,  433,  434,
      417,  434,  415,  414,  413,  412,  411,  408,  407,  406,
      405,  403,  401,  399,  396,  393,  392,  389,  388,  386,
      385,  384,  383,  382,  381,  380,  378,  376,  374,  373,
      372,  371,  368,  367,  366,  365,  364,  363,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  342,  341,  340,  339,  338,  337,

      336,  335,  334,  333,  331,  330,  329,  328,  327,  326,
      325,  324,  322,  320,  319,  318,  317,  316,  314,  313,
      312,  311,  310,  308,  307,  306,  305,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  291,  290,
      289,  288,  286,  285,  282,  281,  280,  279,  276,  274,
      272,  271,  270,  269,  268,  267,  266,  264,  263,  262,
      261,  259,  257,  256,  255,  254,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  234,  230,  229,  228,  227,  226,  225,  223,
      222,  221,  220,  219,  218,  216,  215,  214,  213,  212,

      211,  210,  209,  208,  207,  206,  204,  203,  202,  201,
      199,  198,  197,  196,  195,  194,  193,  190,  189,  188,
      187,  186,  184,  183,  181,  180,  179,  178,  177,  176,
      175,  173,  172,  171,  170,  169,  167,  166,  165,  164,
      162,  160,  159,  158,  157,  156,  155,  154,  151,  150,
      149,  148,  147,  146,  145,  144,  142,  141,  140,  139,
      138,  137,  136,  134,  133,  132,  131,  129,  128,  127,
      126,  125,  123,  122,  121,  120,  119,  118,  115,  114,
      113,  112,  111,  110,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,

       92,   91,   90,   89,   88,   86,   85,   84,   83,   82,
       81,   78,   77,   76,   74,   73,   72,   71,   67,   66,
       65,   64,   63,   61,   60,   59,   58,   57,   54,   53,
       52,   51,   49,   48,   47,   46,   45,   38,   37,   36,
       35,   34,   32,   31,   27,   25,   20,   19,   18,   15,
        9,    7,    5,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "conf-lex.l"
#define INITIAL 0
#line 2 "conf-lex.l"
/* conf.l - Lexer for pdnsd config files
   Copyright (C) 2000, 2001 Thomas Moestl

This file is part of the pdnsd package.

pdnsd is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

pdnsd is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with pdsnd; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.  */

#include <config.h>
#include "conf-parse.h"
#include "consts.h"
#include "rr_types.h"

#if !defined(lint) && !defined(NO_RCSIDS)
static char rcsid[]="$Id: conf-lex.l.in,v 1.22 2001/07/01 21:03:15 tmm Exp $";
#endif

extern YYSTYPE yylval;

int br_level=0;
/* In the location below, %option yylineno is inserted by configure in some 
 * cases.
 * It causes yylineno to be available in flex, which I prefer for error 
 * reporting. It is a little hairy, though, because it is neither part of 
 * the POSIX nor offcially documented in the AT&T lex. Look into configure.in
 * for the implementation. In short, if your lexer generator chokes on this, 
 * you won't get line numbers in the output.*/
#define comment 1

#line 730 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 50 "conf-lex.l"


#line 884 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 432 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 454 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 52 "conf-lex.l"
{sscanf(yytext,"%li",&yylval.num); return NUMBER;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "conf-lex.l"
{return GLOBAL;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "conf-lex.l"
{return SERVER;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "conf-lex.l"
{return RR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "conf-lex.l"
{return NEG;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "conf-lex.l"
{return SOURCE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "conf-lex.l"
{return PERM_CACHE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "conf-lex.l"
{return CACHE_DIR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "conf-lex.l"
{return SERVER_PORT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "conf-lex.l"
{return SERVER_IP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "conf-lex.l"
{return SCHEME_FILE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "conf-lex.l"
{return LINKDOWN_KLUGE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "conf-lex.l"
{return MAX_TTL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "conf-lex.l"
{return MIN_TTL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "conf-lex.l"
{return RUN_AS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "conf-lex.l"
{return STRICT_SETUID;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "conf-lex.l"
{return PARANOID;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "conf-lex.l"
{return STATUS_CTL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "conf-lex.l"
{return DAEMON;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "conf-lex.l"
{return C_TCP_SERVER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "conf-lex.l"
{return PID_FILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "conf-lex.l"
{return C_VERBOSITY;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "conf-lex.l"
{return C_QUERY_METHOD;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "conf-lex.l"
{return RUN_IPV4;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "conf-lex.l"
{return C_DEBUG;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "conf-lex.l"
{return C_CTL_PERMS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "conf-lex.l"
{return C_PROC_LIMIT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "conf-lex.l"
{return C_PROCQ_LIMIT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "conf-lex.l"
{return TCP_QTIMEOUT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "conf-lex.l"
{return C_PAR_QUERIES;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "conf-lex.l"
{return C_RAND_RECS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 "conf-lex.l"
{return NEG_TTL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "conf-lex.l"
{return NEG_RRS_POL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "conf-lex.l"
{return NEG_DOMAIN_POL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "conf-lex.l"
{return QUERY_PORT_START;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "conf-lex.l"
{return QUERY_PORT_END;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "conf-lex.l"
{return IP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "conf-lex.l"
{return PORT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "conf-lex.l"
{return SCHEME;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "conf-lex.l"
{return UPTEST;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "conf-lex.l"
{return TIMEOUT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "conf-lex.l"
{return PING_TIMEOUT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "conf-lex.l"
{return PING_IP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "conf-lex.l"
{return UPTEST_CMD;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "conf-lex.l"
{return INTERVAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "conf-lex.l"
{return INTERFACE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "conf-lex.l"
{return DEVICE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "conf-lex.l"
{return PURGE_CACHE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "conf-lex.l"
{return CACHING;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "conf-lex.l"
{return LEAN_QUERY;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "conf-lex.l"
{return PRESET;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "conf-lex.l"
{return PROXY_ONLY;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "conf-lex.l"
{return INCLUDE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "conf-lex.l"
{return EXCLUDE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "conf-lex.l"
{return POLICY;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "conf-lex.l"
{return LABEL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 111 "conf-lex.l"
{return A;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 112 "conf-lex.l"
{return PTR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "conf-lex.l"
{return MX;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 114 "conf-lex.l"
{return CNAME;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 115 "conf-lex.l"
{return SOA;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "conf-lex.l"
{return NAME;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 117 "conf-lex.l"
{return OWNER;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "conf-lex.l"
{return TTL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 119 "conf-lex.l"
{return TYPES;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 120 "conf-lex.l"
{return FILET;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 121 "conf-lex.l"
{return SERVE_ALIASES;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 122 "conf-lex.l"
{return AUTHREC;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 124 "conf-lex.l"
{return NDOMAIN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 126 "conf-lex.l"
{if ((yylval.num=lookup_const(yytext))!=-1)
						 return CONST; 
					 else if ((yylval.num=rr_tp_byname(yytext))!=-1)
						 return RRTYPE;
					 else {
						 return ERROR;					     
					 }}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 134 "conf-lex.l"
{yylval.nm=(unsigned char *)yytext+1;
					 yylval.nm[strlen((char *)yylval.nm)-1]=(unsigned char)'\0';return STRING;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 136 "conf-lex.l"
{return yytext[0];}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 137 "conf-lex.l"
/*munch munch*/
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 139 "conf-lex.l"
{
						br_level++;
						BEGIN(comment);
					}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "conf-lex.l"
{
						br_level--;
						if (br_level<0)
							return ERROR;
						if (br_level==0)
							BEGIN(INITIAL);
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 150 "conf-lex.l"
/* Delete text in comments, */
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "conf-lex.l"
/* white space, */
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 152 "conf-lex.l"
/* new lines. */
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "conf-lex.l"
{return ERROR;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 155 "conf-lex.l"
ECHO;
	YY_BREAK
#line 1391 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(comment):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 432 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 432 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 431);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 155 "conf-lex.l"


void lex_set_io(FILE *in, FILE *out)
{
	yyin=in;
	yyout=out;
}

int yywrap()
{
	return 1;
}
